### ISSUE TITLE
Setup STLP applications/configurations

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/sln_avona#31]
Configurations needed are:

STLP-UA

- USB for reference audio input
- USB for processed audio output
- USB for device control 
- I2S master mode for processed ASR output to the DAC
- ADEC is default AEC arch
- Remove fixed delay AEC arch all together
- Optional USB for microphone input debug/testing option

STLP-INT

- I2S slave mode for reference audio input
- I2S slave mode for processed audio output
- I2C for device control

**Comment by keithm-xmos** [comment]
INT build needs to be I2C slave

**Comment by xmos-jmccarthy** [comment]
`STLP-UA build needs to output the two reference audio inputs to the DAC.`
Resolved by #49

**Comment by xmos-jmccarthy** [comment]
`STLP-INT build needs to be I2C slave which means some other device must configure the DAC. The RPi will do this.`
Resolved by #51 
Tested with Aardvark.
